name: dartango_admin
description: Admin dashboard for Dartango framework
version: 0.0.1
homepage: https://github.com/yourusername/dartango

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.0
  go_router: ^13.0.0
  flutter_form_builder: ^9.1.0
  data_table_2: ^2.5.0
  fl_chart: ^0.66.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
