name: dartango
description: A Django-inspired full-stack framework for Dart
version: 0.0.1
homepage: https://github.com/yourusername/dartango

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.0
  shelf_cors_headers: ^0.1.5
  postgres: ^3.0.0
  mysql1: ^0.20.0
  sqlite3: ^2.1.0
  crypto: ^3.0.0
  mustache_template: ^2.0.0
  args: ^2.4.0
  path: ^1.8.0
  collection: ^1.18.0
  meta: ^1.11.0
  logging: ^1.2.0
  yaml: ^3.1.0
  uuid: ^4.2.0

dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.0
  mockito: ^5.4.0
  lints: ^3.0.0
