name: ecommerce_demo
description: Dartango E-commerce Demo - Showcasing Django-style framework for Dart
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  
dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

# This demo shows how to create a full e-commerce platform using Dartango
# Features demonstrated:
# - Complete ORM with model relationships  
# - Django-style admin interface
# - RESTful API endpoints
# - User authentication and permissions
# - Database migrations and seeding
# - Custom admin actions and fieldsets